/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ulises
 */
public class VistaPrincipal extends javax.swing.JFrame {

    
    private DefaultTableModel tableModel;
    private DefaultTableModel tableModel2;
    
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Contenedor = new javax.swing.JPanel();
        PanelOpciones = new javax.swing.JPanel();
        BotonPanelArbitros = new javax.swing.JButton();
        BotonPanelEquipos = new javax.swing.JButton();
        BotonPanelJugadores = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PanelArbitros = new javax.swing.JPanel();
        BotonVolverArbitros = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaArbitros = new javax.swing.JTable();
        BotonCargarArbitro = new javax.swing.JButton();
        BotonEliminarArbitro = new javax.swing.JButton();
        BotonModificarArbitro = new javax.swing.JButton();
        botonFiltrarArbitros = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        barraFiltradoArbitros = new javax.swing.JTextField();
        barraOrdenamientoArbitros = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        botonDeOrdenamientoArbitros = new javax.swing.JButton();
        PanelJugadores = new javax.swing.JPanel();
        BotonVolverJugadores = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaJugadores = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        BotonCargarJugador = new javax.swing.JButton();
        BotonEliminarJugador = new javax.swing.JButton();
        BotonModificarJugador = new javax.swing.JButton();
        botonFiltradoJugadores = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        barraOrdenamientoJugadores = new javax.swing.JComboBox<>();
        botonOrdenarJugadores = new javax.swing.JButton();
        barraFiltradoJugadores = new javax.swing.JTextField();
        PanelEquipos = new javax.swing.JPanel();
        BotonVolverEquipos = new javax.swing.JButton();
        PanelCargarJugador = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CampoNombreCargar = new javax.swing.JTextField();
        CampoApellidoCargar = new javax.swing.JTextField();
        CampoFecNacCargar = new javax.swing.JTextField();
        CampoNacionalidadCargar = new javax.swing.JTextField();
        CampoTarjAmarillasCargar = new javax.swing.JTextField();
        CampoCantGolesCargar = new javax.swing.JTextField();
        CampoTarjRojasCargar = new javax.swing.JTextField();
        BotonVolverCargarJugador = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        botonCargarJugador = new javax.swing.JButton();
        PanelCargarArbitro = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        InternacionalSiCargarArbitro = new javax.swing.JCheckBox();
        InternacionalNoCargarArbitro = new javax.swing.JCheckBox();
        CampoNombreCargarArbitro = new javax.swing.JTextField();
        CampoApellidoCargarArbitro = new javax.swing.JTextField();
        CampoFecNacCargarArbitro = new javax.swing.JTextField();
        CampoNacionalidadCargarArbitro = new javax.swing.JTextField();
        CampoTarjSacadasCargarArbitro = new javax.swing.JTextField();
        BotonVolverCargarArbitro = new javax.swing.JButton();
        PanelModificarJugador = new javax.swing.JPanel();
        BotonVolverModificarJugador = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        modificarGoles = new javax.swing.JTextField();
        modificarTarjetasAmarillas = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        modificarPosicion = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        PanelModificarArbitro = new javax.swing.JPanel();
        BotonVolverModificarArbitro = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(962, 530));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Contenedor.setMaximumSize(new java.awt.Dimension(1920, 1080));
        Contenedor.setPreferredSize(new java.awt.Dimension(1920, 1080));
        Contenedor.setLayout(new java.awt.CardLayout());

        PanelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonPanelArbitros.setText("ARBITROS");
        BotonPanelArbitros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPanelArbitrosActionPerformed(evt);
            }
        });
        PanelOpciones.add(BotonPanelArbitros, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 248, 150, 90));

        BotonPanelEquipos.setText("EQUIPOS");
        BotonPanelEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPanelEquiposActionPerformed(evt);
            }
        });
        PanelOpciones.add(BotonPanelEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 376, 150, 90));

        BotonPanelJugadores.setText("JUGADORES");
        BotonPanelJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPanelJugadoresMouseClicked(evt);
            }
        });
        BotonPanelJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPanelJugadoresActionPerformed(evt);
            }
        });
        PanelOpciones.add(BotonPanelJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 150, 90));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel3.setText("TORNEO FUTBOL 5");
        PanelOpciones.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, 56));

        Contenedor.add(PanelOpciones, "card2");

        PanelArbitros.setMinimumSize(new java.awt.Dimension(1920, 1080));
        PanelArbitros.setPreferredSize(new java.awt.Dimension(1920, 1080));

        BotonVolverArbitros.setBackground(new java.awt.Color(255, 153, 153));
        BotonVolverArbitros.setText("Volver");
        BotonVolverArbitros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverArbitrosActionPerformed(evt);
            }
        });

        TablaArbitros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TablaArbitros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Apellido y Nombre", "Documento", "Nacimiento", "Nacionalidad", "Tarjetas sacadas", "Internacional"
            }
        ));
        jScrollPane3.setViewportView(TablaArbitros);

        BotonCargarArbitro.setBackground(new java.awt.Color(153, 255, 153));
        BotonCargarArbitro.setText("Cargar Arbitro");
        BotonCargarArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCargarArbitroActionPerformed(evt);
            }
        });

        BotonEliminarArbitro.setBackground(new java.awt.Color(255, 153, 153));
        BotonEliminarArbitro.setText("Eliminar Arbitro");
        BotonEliminarArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarArbitroActionPerformed(evt);
            }
        });

        BotonModificarArbitro.setBackground(new java.awt.Color(255, 255, 204));
        BotonModificarArbitro.setText("Modificar Arbitro");
        BotonModificarArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarArbitroActionPerformed(evt);
            }
        });

        botonFiltrarArbitros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonFiltrarArbitros.setText("Filtrar");
        botonFiltrarArbitros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFiltrarArbitrosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Panel de árbitros");

        barraFiltradoArbitros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        barraFiltradoArbitros.setText("Ingrese la informacion del árbitro que desea buscar");
        barraFiltradoArbitros.setPreferredSize(new java.awt.Dimension(290, 22));
        barraFiltradoArbitros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barraFiltradoArbitrosMouseClicked(evt);
            }
        });
        barraFiltradoArbitros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraFiltradoArbitrosActionPerformed(evt);
            }
        });

        barraOrdenamientoArbitros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        barraOrdenamientoArbitros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre A-Z", "Nombre Z-A", "Apellido A-Z", "Apellido Z-A", "Nacimiento", "Nacionalidad", "Tarjetas Sacadas", "Internacional" }));

        jLabel19.setText("Opciones de Ordenamiento");

        botonDeOrdenamientoArbitros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonDeOrdenamientoArbitros.setText("Ordenar");

        javax.swing.GroupLayout PanelArbitrosLayout = new javax.swing.GroupLayout(PanelArbitros);
        PanelArbitros.setLayout(PanelArbitrosLayout);
        PanelArbitrosLayout.setHorizontalGroup(
            PanelArbitrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelArbitrosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PanelArbitrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelArbitrosLayout.createSequentialGroup()
                        .addComponent(barraFiltradoArbitros, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonFiltrarArbitros)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelArbitrosLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1510, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(PanelArbitrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelArbitrosLayout.createSequentialGroup()
                                .addGroup(PanelArbitrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(BotonEliminarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelArbitrosLayout.createSequentialGroup()
                                        .addComponent(barraOrdenamientoArbitros, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonDeOrdenamientoArbitros))
                                    .addComponent(BotonModificarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonCargarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(127, 127, 127))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelArbitrosLayout.createSequentialGroup()
                                .addComponent(BotonVolverArbitros, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))))
            .addGroup(PanelArbitrosLayout.createSequentialGroup()
                .addGap(867, 867, 867)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelArbitrosLayout.setVerticalGroup(
            PanelArbitrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelArbitrosLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(138, 138, 138)
                .addGroup(PanelArbitrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barraFiltradoArbitros, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(botonFiltrarArbitros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelArbitrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelArbitrosLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelArbitrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonDeOrdenamientoArbitros)
                            .addComponent(barraOrdenamientoArbitros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonCargarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonModificarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonEliminarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(BotonVolverArbitros, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        Contenedor.add(PanelArbitros, "card3");

        PanelJugadores.setMaximumSize(new java.awt.Dimension(1920, 1080));
        PanelJugadores.setPreferredSize(new java.awt.Dimension(1920, 1080));

        BotonVolverJugadores.setBackground(new java.awt.Color(255, 153, 153));
        BotonVolverJugadores.setText("Volver");
        BotonVolverJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverJugadoresActionPerformed(evt);
            }
        });

        TablaJugadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TablaJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Apellido y Nombre", "Documento", "Nacimiento", "Nacionalidad", "Club actual", "Posición", "Goles", "Tarjetas Amarillas", "Tarjetas Rojas"
            }
        ));
        jScrollPane2.setViewportView(TablaJugadores);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Panel de jugadores");

        BotonCargarJugador.setBackground(new java.awt.Color(153, 255, 153));
        BotonCargarJugador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonCargarJugador.setText(" Cargar Jugador");
        BotonCargarJugador.setMaximumSize(new java.awt.Dimension(126, 22));
        BotonCargarJugador.setMinimumSize(new java.awt.Dimension(126, 22));
        BotonCargarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCargarJugadorActionPerformed(evt);
            }
        });

        BotonEliminarJugador.setBackground(new java.awt.Color(255, 153, 153));
        BotonEliminarJugador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonEliminarJugador.setText("Eliminar Jugador");
        BotonEliminarJugador.setMaximumSize(new java.awt.Dimension(126, 22));
        BotonEliminarJugador.setMinimumSize(new java.awt.Dimension(126, 22));
        BotonEliminarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarJugadorActionPerformed(evt);
            }
        });

        BotonModificarJugador.setBackground(new java.awt.Color(255, 255, 204));
        BotonModificarJugador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonModificarJugador.setText("Modificar Jugador");
        BotonModificarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarJugadorActionPerformed(evt);
            }
        });

        botonFiltradoJugadores.setBackground(new java.awt.Color(242, 242, 242));
        botonFiltradoJugadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonFiltradoJugadores.setText("Filtrar");
        botonFiltradoJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFiltradoJugadoresActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Opciones de ordenamiento:");

        barraOrdenamientoJugadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        barraOrdenamientoJugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apellido A-Z", "Apellido Z-A", "Nombre A-Z", "Nombre Z-A", "Edad", "Nacionalidad", "Club actual", "Posición", "Goles", "Tarjetas amarillas", "Tarjetas rojas" }));

        botonOrdenarJugadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonOrdenarJugadores.setText("Ordenar");
        botonOrdenarJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrdenarJugadoresActionPerformed(evt);
            }
        });

        barraFiltradoJugadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        barraFiltradoJugadores.setText("Ingrese la información del jugador que desea buscar");

        javax.swing.GroupLayout PanelJugadoresLayout = new javax.swing.GroupLayout(PanelJugadores);
        PanelJugadores.setLayout(PanelJugadoresLayout);
        PanelJugadoresLayout.setHorizontalGroup(
            PanelJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJugadoresLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PanelJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1553, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelJugadoresLayout.createSequentialGroup()
                        .addComponent(barraFiltradoJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonFiltradoJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelJugadoresLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelJugadoresLayout.createSequentialGroup()
                                .addGroup(PanelJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(barraOrdenamientoJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonModificarJugador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonCargarJugador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonEliminarJugador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonOrdenarJugadores))
                            .addComponent(jLabel25))
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelJugadoresLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonVolverJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
            .addGroup(PanelJugadoresLayout.createSequentialGroup()
                .addGap(856, 856, 856)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelJugadoresLayout.setVerticalGroup(
            PanelJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelJugadoresLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(0, 171, Short.MAX_VALUE)
                .addGroup(PanelJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonFiltradoJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barraFiltradoJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelJugadoresLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addGroup(PanelJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barraOrdenamientoJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonOrdenarJugadores))
                        .addGap(337, 337, 337)
                        .addGroup(PanelJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonVolverJugadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelJugadoresLayout.createSequentialGroup()
                                .addComponent(BotonCargarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BotonModificarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BotonEliminarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        Contenedor.add(PanelJugadores, "card4");

        BotonVolverEquipos.setText("Volver");
        BotonVolverEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverEquiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEquiposLayout = new javax.swing.GroupLayout(PanelEquipos);
        PanelEquipos.setLayout(PanelEquiposLayout);
        PanelEquiposLayout.setHorizontalGroup(
            PanelEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEquiposLayout.createSequentialGroup()
                .addContainerGap(993, Short.MAX_VALUE)
                .addComponent(BotonVolverEquipos)
                .addGap(855, 855, 855))
        );
        PanelEquiposLayout.setVerticalGroup(
            PanelEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEquiposLayout.createSequentialGroup()
                .addContainerGap(557, Short.MAX_VALUE)
                .addComponent(BotonVolverEquipos)
                .addGap(501, 501, 501))
        );

        Contenedor.add(PanelEquipos, "card5");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Apellido:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Fecha de nacimiento:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nacionalidad:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delantero", "MedioCampo", "Defensor", "Arquero" }));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Posicion:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Club:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boca", "River", "Racing", "San Lorenzo", "Independiente", "Estudiantes", "Huracan", "Newell's", "Velez", "Rosario Central" }));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Cantidad de goles:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Tarjetas Amarillas:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Tarjetas Rojas:");

        CampoNombreCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNombreCargarActionPerformed(evt);
            }
        });

        CampoApellidoCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoApellidoCargarActionPerformed(evt);
            }
        });

        BotonVolverCargarJugador.setBackground(new java.awt.Color(255, 153, 153));
        BotonVolverCargarJugador.setText("Volver");
        BotonVolverCargarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverCargarJugadorActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel20.setText("Cargar Jugador");

        botonCargarJugador.setBackground(new java.awt.Color(153, 255, 153));
        botonCargarJugador.setText("Cargar");
        botonCargarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarJugadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCargarJugadorLayout = new javax.swing.GroupLayout(PanelCargarJugador);
        PanelCargarJugador.setLayout(PanelCargarJugadorLayout);
        PanelCargarJugadorLayout.setHorizontalGroup(
            PanelCargarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCargarJugadorLayout.createSequentialGroup()
                .addGroup(PanelCargarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCargarJugadorLayout.createSequentialGroup()
                        .addGap(695, 695, 695)
                        .addComponent(BotonVolverCargarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(botonCargarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCargarJugadorLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(PanelCargarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(31, 31, 31)
                        .addGroup(PanelCargarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CampoApellidoCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoFecNacCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoNombreCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoNacionalidadCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(PanelCargarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelCargarJugadorLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CampoTarjRojasCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelCargarJugadorLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CampoTarjAmarillasCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20)
                            .addGroup(PanelCargarJugadorLayout.createSequentialGroup()
                                .addGroup(PanelCargarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PanelCargarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelCargarJugadorLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(28, 28, 28)
                                .addComponent(CampoCantGolesCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(485, Short.MAX_VALUE))
        );
        PanelCargarJugadorLayout.setVerticalGroup(
            PanelCargarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCargarJugadorLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel20)
                .addGap(63, 63, 63)
                .addGroup(PanelCargarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNombreCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCargarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addGroup(PanelCargarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(CampoApellidoCargar)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(PanelCargarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoCantGolesCargar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addGroup(PanelCargarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CampoFecNacCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(PanelCargarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCargarJugadorLayout.createSequentialGroup()
                        .addComponent(CampoNacionalidadCargar)
                        .addGap(79, 79, 79)
                        .addGroup(PanelCargarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoTarjAmarillasCargar)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(PanelCargarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(CampoTarjRojasCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(253, 253, 253))
                    .addGroup(PanelCargarJugadorLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(PanelCargarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonVolverCargarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCargarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(490, 490, 490))
        );

        Contenedor.add(PanelCargarJugador, "card6");

        jLabel13.setText("Nombre:");

        jLabel14.setText("Apellido:");

        jLabel15.setText("Fecha de Nacimiento:");

        jLabel16.setText("Nacionalidad:");

        jLabel17.setText("Tarjetas Sacadas:");

        jLabel18.setText("Internacional:");

        InternacionalSiCargarArbitro.setText("SI");
        InternacionalSiCargarArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InternacionalSiCargarArbitroActionPerformed(evt);
            }
        });

        InternacionalNoCargarArbitro.setText("NO");
        InternacionalNoCargarArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InternacionalNoCargarArbitroActionPerformed(evt);
            }
        });

        CampoNombreCargarArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNombreCargarArbitroActionPerformed(evt);
            }
        });

        BotonVolverCargarArbitro.setText("Volver");
        BotonVolverCargarArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverCargarArbitroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCargarArbitroLayout = new javax.swing.GroupLayout(PanelCargarArbitro);
        PanelCargarArbitro.setLayout(PanelCargarArbitroLayout);
        PanelCargarArbitroLayout.setHorizontalGroup(
            PanelCargarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCargarArbitroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCargarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCargarArbitroLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoFecNacCargarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCargarArbitroLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoNacionalidadCargarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCargarArbitroLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoTarjSacadasCargarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCargarArbitroLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InternacionalSiCargarArbitro)
                        .addGap(18, 18, 18)
                        .addComponent(InternacionalNoCargarArbitro))
                    .addGroup(PanelCargarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCargarArbitroLayout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CampoNombreCargarArbitro))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCargarArbitroLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CampoApellidoCargarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCargarArbitroLayout.createSequentialGroup()
                .addContainerGap(954, Short.MAX_VALUE)
                .addComponent(BotonVolverCargarArbitro)
                .addGap(894, 894, 894))
        );
        PanelCargarArbitroLayout.setVerticalGroup(
            PanelCargarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCargarArbitroLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(PanelCargarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(CampoNombreCargarArbitro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCargarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(CampoApellidoCargarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCargarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(CampoFecNacCargarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCargarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(CampoNacionalidadCargarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCargarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(CampoTarjSacadasCargarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCargarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(InternacionalSiCargarArbitro)
                    .addComponent(InternacionalNoCargarArbitro))
                .addGap(306, 306, 306)
                .addComponent(BotonVolverCargarArbitro)
                .addContainerGap(490, Short.MAX_VALUE))
        );

        Contenedor.add(PanelCargarArbitro, "card7");

        BotonVolverModificarJugador.setBackground(new java.awt.Color(255, 153, 153));
        BotonVolverModificarJugador.setText("Volver");
        BotonVolverModificarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverModificarJugadorActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jLabel21.setText("Modificar Jugador");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Tarjetas amarillas:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Goles:");

        modificarGoles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modificarGoles.setText("Ingrese los goles");
        modificarGoles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarGolesMouseClicked(evt);
            }
        });

        modificarTarjetasAmarillas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modificarTarjetasAmarillas.setText("Ingrese las tarjetas amarillas");
        modificarTarjetasAmarillas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarTarjetasAmarillasMouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("Posición:");

        modificarPosicion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modificarPosicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delantero", "Mediocampo", "Defensor", "Arquero" }));

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelModificarJugadorLayout = new javax.swing.GroupLayout(PanelModificarJugador);
        PanelModificarJugador.setLayout(PanelModificarJugadorLayout);
        PanelModificarJugadorLayout.setHorizontalGroup(
            PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelModificarJugadorLayout.createSequentialGroup()
                .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelModificarJugadorLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(62, 62, 62)
                        .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modificarGoles)
                            .addComponent(modificarTarjetasAmarillas, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(BotonVolverModificarJugador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelModificarJugadorLayout.createSequentialGroup()
                                .addGap(293, 293, 293)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelModificarJugadorLayout.createSequentialGroup()
                                .addGap(418, 418, 418)
                                .addComponent(modificarPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelModificarJugadorLayout.createSequentialGroup()
                        .addGap(863, 863, 863)
                        .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel21))))
                .addContainerGap(498, Short.MAX_VALUE))
        );
        PanelModificarJugadorLayout.setVerticalGroup(
            PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModificarJugadorLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelModificarJugadorLayout.createSequentialGroup()
                        .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelModificarJugadorLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelModificarJugadorLayout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(jLabel22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModificarJugadorLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel24)
                                            .addComponent(modificarPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(modificarTarjetasAmarillas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(jLabel23))
                    .addComponent(modificarGoles, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131)
                .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonVolverModificarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(595, Short.MAX_VALUE))
        );

        Contenedor.add(PanelModificarJugador, "card8");

        BotonVolverModificarArbitro.setText("Volver");
        BotonVolverModificarArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverModificarArbitroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelModificarArbitroLayout = new javax.swing.GroupLayout(PanelModificarArbitro);
        PanelModificarArbitro.setLayout(PanelModificarArbitroLayout);
        PanelModificarArbitroLayout.setHorizontalGroup(
            PanelModificarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
            .addGroup(PanelModificarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelModificarArbitroLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BotonVolverModificarArbitro)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelModificarArbitroLayout.setVerticalGroup(
            PanelModificarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(PanelModificarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelModificarArbitroLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(BotonVolverModificarArbitro)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Contenedor.add(PanelModificarArbitro, "card9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonPanelJugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPanelJugadoresMouseClicked
               
    }//GEN-LAST:event_BotonPanelJugadoresMouseClicked

    private void BotonPanelJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPanelJugadoresActionPerformed
        Contenedor.removeAll();
        Contenedor.add(PanelJugadores);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_BotonPanelJugadoresActionPerformed

    private void BotonPanelArbitrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPanelArbitrosActionPerformed
        Contenedor.removeAll();
        Contenedor.add(PanelArbitros);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_BotonPanelArbitrosActionPerformed

    private void BotonPanelEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPanelEquiposActionPerformed
        Contenedor.removeAll();
        Contenedor.add(PanelEquipos);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_BotonPanelEquiposActionPerformed

    private void BotonVolverArbitrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverArbitrosActionPerformed
        Contenedor.removeAll();
        Contenedor.add(PanelOpciones);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_BotonVolverArbitrosActionPerformed

    private void BotonVolverJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverJugadoresActionPerformed
        Contenedor.removeAll();
        Contenedor.add(PanelOpciones);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_BotonVolverJugadoresActionPerformed

    private void BotonVolverEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverEquiposActionPerformed
        Contenedor.removeAll();
        Contenedor.add(PanelOpciones);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_BotonVolverEquiposActionPerformed

    private void BotonEliminarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarJugadorActionPerformed
        Contenedor.removeAll();
        Contenedor.add(PanelModificarJugador);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_BotonEliminarJugadorActionPerformed

    private void BotonCargarArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCargarArbitroActionPerformed
        Contenedor.removeAll();
        Contenedor.add(PanelCargarArbitro);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_BotonCargarArbitroActionPerformed

    private void botonFiltrarArbitrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFiltrarArbitrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonFiltrarArbitrosActionPerformed

    private void botonFiltradoJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFiltradoJugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonFiltradoJugadoresActionPerformed

    private void BotonCargarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCargarJugadorActionPerformed
        Contenedor.removeAll();
        Contenedor.add(PanelCargarJugador);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_BotonCargarJugadorActionPerformed

    private void BotonModificarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarJugadorActionPerformed
        Contenedor.removeAll();
        Contenedor.add(PanelModificarJugador);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_BotonModificarJugadorActionPerformed

    private void CampoNombreCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNombreCargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNombreCargarActionPerformed

    private void CampoApellidoCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoApellidoCargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoApellidoCargarActionPerformed

    private void InternacionalSiCargarArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InternacionalSiCargarArbitroActionPerformed
        if (InternacionalSiCargarArbitro.isSelected()) {
            InternacionalNoCargarArbitro.setSelected(false);
        }
    }//GEN-LAST:event_InternacionalSiCargarArbitroActionPerformed

    private void CampoNombreCargarArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNombreCargarArbitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNombreCargarArbitroActionPerformed

    private void BotonVolverCargarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverCargarJugadorActionPerformed
        Contenedor.removeAll();
        Contenedor.add(PanelJugadores);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_BotonVolverCargarJugadorActionPerformed

    private void BotonVolverCargarArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverCargarArbitroActionPerformed
        Contenedor.removeAll();
        Contenedor.add(PanelArbitros);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_BotonVolverCargarArbitroActionPerformed

    private void BotonEliminarArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarArbitroActionPerformed
        try{
            if(TablaArbitros.getSelectedRow()!=-1){ //Hay una fila seleccionada, por lo tanto se procede a eliminar el arbitro
                
            }else{
                JOptionPane.showMessageDialog(null,"Seleccione un arbitro.","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_BotonEliminarArbitroActionPerformed

    private void BotonModificarArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarArbitroActionPerformed
        Contenedor.removeAll();
        Contenedor.add(PanelModificarArbitro);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_BotonModificarArbitroActionPerformed

    private void BotonVolverModificarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverModificarJugadorActionPerformed
        Contenedor.removeAll();
        Contenedor.add(PanelJugadores);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_BotonVolverModificarJugadorActionPerformed

    private void BotonVolverModificarArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverModificarArbitroActionPerformed
        Contenedor.removeAll();
        Contenedor.add(PanelArbitros);
        Contenedor.repaint();
        Contenedor.revalidate();
    }//GEN-LAST:event_BotonVolverModificarArbitroActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Quiere guardar los cambios antes de salir?", "Atención", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (respuesta == JOptionPane.OK_OPTION) {
            //Aqui se guardarian los datos en los archivos
        }
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void InternacionalNoCargarArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InternacionalNoCargarArbitroActionPerformed
        if (InternacionalNoCargarArbitro.isSelected()) {
            InternacionalSiCargarArbitro.setSelected(false);
        }
    }//GEN-LAST:event_InternacionalNoCargarArbitroActionPerformed

    private void barraFiltradoArbitrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraFiltradoArbitrosMouseClicked
        barraFiltradoArbitros.setText("");
    }//GEN-LAST:event_barraFiltradoArbitrosMouseClicked

    private void barraFiltradoArbitrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraFiltradoArbitrosActionPerformed
        
    }//GEN-LAST:event_barraFiltradoArbitrosActionPerformed

    private void botonCargarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCargarJugadorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void modificarTarjetasAmarillasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarTarjetasAmarillasMouseClicked
        modificarTarjetasAmarillas.setText("");
    }//GEN-LAST:event_modificarTarjetasAmarillasMouseClicked

    private void modificarGolesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarGolesMouseClicked
        modificarGoles.setText("");
    }//GEN-LAST:event_modificarGolesMouseClicked

    private void botonOrdenarJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrdenarJugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonOrdenarJugadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCargarArbitro;
    private javax.swing.JButton BotonCargarJugador;
    private javax.swing.JButton BotonEliminarArbitro;
    private javax.swing.JButton BotonEliminarJugador;
    private javax.swing.JButton BotonModificarArbitro;
    private javax.swing.JButton BotonModificarJugador;
    private javax.swing.JButton BotonPanelArbitros;
    private javax.swing.JButton BotonPanelEquipos;
    private javax.swing.JButton BotonPanelJugadores;
    private javax.swing.JButton BotonVolverArbitros;
    private javax.swing.JButton BotonVolverCargarArbitro;
    private javax.swing.JButton BotonVolverCargarJugador;
    private javax.swing.JButton BotonVolverEquipos;
    private javax.swing.JButton BotonVolverJugadores;
    private javax.swing.JButton BotonVolverModificarArbitro;
    private javax.swing.JButton BotonVolverModificarJugador;
    private javax.swing.JTextField CampoApellidoCargar;
    private javax.swing.JTextField CampoApellidoCargarArbitro;
    private javax.swing.JTextField CampoCantGolesCargar;
    private javax.swing.JTextField CampoFecNacCargar;
    private javax.swing.JTextField CampoFecNacCargarArbitro;
    private javax.swing.JTextField CampoNacionalidadCargar;
    private javax.swing.JTextField CampoNacionalidadCargarArbitro;
    private javax.swing.JTextField CampoNombreCargar;
    private javax.swing.JTextField CampoNombreCargarArbitro;
    private javax.swing.JTextField CampoTarjAmarillasCargar;
    private javax.swing.JTextField CampoTarjRojasCargar;
    private javax.swing.JTextField CampoTarjSacadasCargarArbitro;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JCheckBox InternacionalNoCargarArbitro;
    private javax.swing.JCheckBox InternacionalSiCargarArbitro;
    private javax.swing.JPanel PanelArbitros;
    private javax.swing.JPanel PanelCargarArbitro;
    private javax.swing.JPanel PanelCargarJugador;
    private javax.swing.JPanel PanelEquipos;
    private javax.swing.JPanel PanelJugadores;
    private javax.swing.JPanel PanelModificarArbitro;
    private javax.swing.JPanel PanelModificarJugador;
    private javax.swing.JPanel PanelOpciones;
    private javax.swing.JTable TablaArbitros;
    private javax.swing.JTable TablaJugadores;
    private javax.swing.JTextField barraFiltradoArbitros;
    private javax.swing.JTextField barraFiltradoJugadores;
    private javax.swing.JComboBox<String> barraOrdenamientoArbitros;
    private javax.swing.JComboBox<String> barraOrdenamientoJugadores;
    private javax.swing.JButton botonCargarJugador;
    private javax.swing.JButton botonDeOrdenamientoArbitros;
    private javax.swing.JButton botonFiltradoJugadores;
    private javax.swing.JButton botonFiltrarArbitros;
    private javax.swing.JButton botonOrdenarJugadores;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField modificarGoles;
    private javax.swing.JComboBox<String> modificarPosicion;
    private javax.swing.JTextField modificarTarjetasAmarillas;
    // End of variables declaration//GEN-END:variables
}
